site_name: PyFLP
site_url: https://pyflp.rtfd.io/
site_description: FL Studio project file parser
site_author: demberto
repo_url: https://github.com/demberto/PyFLP/
copyright: (c) demberto 2021
nav:
  - Overview: index.md
  - Installation: installation.md
  - Handbook: handbook.md
  - Models: models.md
  - FLP Format: flp-format.md
  - Contributing: contributing.md
  - Report a bug: https://github.com/demberto/PyFLP/issues
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - include-markdown
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 5
            show_bases: no
            show_if_no_docstring: yes
            show_root_full_path: no
            show_root_heading: yes
            show_source: no
      watch:
        - pyflp
